/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImportRouteImport } from './routes/import'
import { Route as CoverageRouteImport } from './routes/coverage'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientsIndexRouteImport } from './routes/clients/index'
import { Route as ClientsNewRouteImport } from './routes/clients/new'
import { Route as ClientsClientIdRouteImport } from './routes/clients/$clientId'
import { Route as ClientsClientIdDeadlinesNewRouteImport } from './routes/clients/$clientId/deadlines/new'

const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverageRoute = CoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdDeadlinesNewRoute =
  ClientsClientIdDeadlinesNewRouteImport.update({
    id: '/deadlines/new',
    path: '/deadlines/new',
    getParentRoute: () => ClientsClientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coverage': typeof CoverageRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/clients/$clientId': typeof ClientsClientIdRouteWithChildren
  '/clients/new': typeof ClientsNewRoute
  '/clients/': typeof ClientsIndexRoute
  '/clients/$clientId/deadlines/new': typeof ClientsClientIdDeadlinesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coverage': typeof CoverageRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/clients/$clientId': typeof ClientsClientIdRouteWithChildren
  '/clients/new': typeof ClientsNewRoute
  '/clients': typeof ClientsIndexRoute
  '/clients/$clientId/deadlines/new': typeof ClientsClientIdDeadlinesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coverage': typeof CoverageRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/clients/$clientId': typeof ClientsClientIdRouteWithChildren
  '/clients/new': typeof ClientsNewRoute
  '/clients/': typeof ClientsIndexRoute
  '/clients/$clientId/deadlines/new': typeof ClientsClientIdDeadlinesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coverage'
    | '/import'
    | '/login'
    | '/progress'
    | '/clients/$clientId'
    | '/clients/new'
    | '/clients/'
    | '/clients/$clientId/deadlines/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coverage'
    | '/import'
    | '/login'
    | '/progress'
    | '/clients/$clientId'
    | '/clients/new'
    | '/clients'
    | '/clients/$clientId/deadlines/new'
  id:
    | '__root__'
    | '/'
    | '/coverage'
    | '/import'
    | '/login'
    | '/progress'
    | '/clients/$clientId'
    | '/clients/new'
    | '/clients/'
    | '/clients/$clientId/deadlines/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoverageRoute: typeof CoverageRoute
  ImportRoute: typeof ImportRoute
  LoginRoute: typeof LoginRoute
  ProgressRoute: typeof ProgressRoute
  ClientsClientIdRoute: typeof ClientsClientIdRouteWithChildren
  ClientsNewRoute: typeof ClientsNewRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coverage': {
      id: '/coverage'
      path: '/coverage'
      fullPath: '/coverage'
      preLoaderRoute: typeof CoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId/deadlines/new': {
      id: '/clients/$clientId/deadlines/new'
      path: '/deadlines/new'
      fullPath: '/clients/$clientId/deadlines/new'
      preLoaderRoute: typeof ClientsClientIdDeadlinesNewRouteImport
      parentRoute: typeof ClientsClientIdRoute
    }
  }
}

interface ClientsClientIdRouteChildren {
  ClientsClientIdDeadlinesNewRoute: typeof ClientsClientIdDeadlinesNewRoute
}

const ClientsClientIdRouteChildren: ClientsClientIdRouteChildren = {
  ClientsClientIdDeadlinesNewRoute: ClientsClientIdDeadlinesNewRoute,
}

const ClientsClientIdRouteWithChildren = ClientsClientIdRoute._addFileChildren(
  ClientsClientIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoverageRoute: CoverageRoute,
  ImportRoute: ImportRoute,
  LoginRoute: LoginRoute,
  ProgressRoute: ProgressRoute,
  ClientsClientIdRoute: ClientsClientIdRouteWithChildren,
  ClientsNewRoute: ClientsNewRoute,
  ClientsIndexRoute: ClientsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
